import numpy as np
arr = np.array("addition and subition of two array")
add = np.array([1, 2, 3, 4])
sub = np.array([4, 3, 2, 1])
result_add = np.add(add, sub)
result_sub = np.subtract(add, sub)
print("Addition of two arrays:", result_add)
print("Subtraction of two arrays:", result_sub)
nummpy=np.array("sort in ascending order")
num = np.array([5, 2, 9, 1, 5, 6])
sorted_num = np.sort(num)
print("Sorted array in ascending order:", sorted_num)
import numpy as np
arr = np.array("find the maximum and minimum value in an array")
num = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
max_value = np.max(num)
min_value = np.min(num)
print("Maximum value in the array:", max_value)
print("Minimum value in the array:", min_value)
import numpy as np
arr = np.array("merge two arrays")
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
merged_array = np.concatenate((array1, array2))
print("Merged array:", merged_array)
import numpy as np
arr = np.array("reshape an array")
num = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = num.reshape((2, 3))
print("Reshaped array:\n", reshaped_array)
import numpy as np
arr = np.array("calculate the mean and standard deviation of an array")
num = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(num)
std_deviation = np.std(num)
print("Mean of the array:", mean_value)
print("Standard deviation of the array:", std_deviation)
numpy.mainloop()